# ─────────────────────────────────────────────────────────────────────
#  「✦ HYPERPAPER CONFIG ✦ 」
# ─────────────────────────────────────────────────────────────────────

# ── WALLPAPER ────────────────────────────────────────────────────────
wallpaper {
    monitor =
    path = /home/fiidev/walls/clouds.jpg
}

# ── GENERAL ──────────────────────────────────────────────────────────
splash = false
ipc = on
